# Generated by Django 5.0.1 on 2024-07-31 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('document_type', models.CharField(blank=True, max_length=100, null=True)),
                ('adhar_number', models.CharField(blank=True, max_length=12, null=True)),
                ('adhar_image', models.ImageField(blank=True, null=True, upload_to='adhar_images/')),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('pan_image', models.ImageField(blank=True, null=True, upload_to='pan_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
