# Generated by Django 5.0.1 on 2024-08-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycverification', '0002_kycdetail_investment_kycdetail_nfts_kycdetail_web3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdetail',
            name='pan_image',
        ),
        migrations.AddField(
            model_name='kycdetail',
            name='pan_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='pan_images/back/'),
        ),
        migrations.AddField(
            model_name='kycdetail',
            name='pan_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='pan_images/front/'),
        ),
    ]
