# Generated by Django 5.0.1 on 2024-08-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycverification', '0003_remove_kycdetail_pan_image_kycdetail_pan_back_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycdetail',
            name='adhar_image',
        ),
        migrations.AddField(
            model_name='kycdetail',
            name='adhar_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='adhar_images/back/'),
        ),
        migrations.AddField(
            model_name='kycdetail',
            name='adhar_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='adhar_images/front/'),
        ),
    ]
