# Generated by Django 5.0.1 on 2024-08-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kycverification', '0005_alter_kycdetail_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kycdetail',
            table='kyc',
        ),
    ]
