# Generated by Django 5.0.1 on 2024-08-01 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycdetail',
            name='investment',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='kycdetail',
            name='nfts',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='kycdetail',
            name='web3',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
