# Generated by Django 5.0.1 on 2024-08-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_kycdetail_adhar_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kycdetail',
            table='users',
        ),
    ]
