# Generated by Django 5.0.1 on 2024-08-05 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users_kycdetail',
        ),
    ]
