# Generated by Django 5.0.1 on 2024-08-05 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='users_details',
        ),
    ]
