# Generated by Django 5.0.1 on 2024-08-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kyc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('kyc_id', models.CharField(max_length=100, unique=True)),
                ('document_number', models.CharField(max_length=100)),
                ('document_front_image', models.ImageField(upload_to='documents/')),
                ('document_back_image', models.ImageField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'db_table': 'kyc_details',
            },
        ),
    ]
